// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package domain

import (
	"errors"
	"fmt"
)

const (
	// HyprlandEventTypeActivewindow is a HyprlandEventType of type activewindow.
	HyprlandEventTypeActivewindow HyprlandEventType = "activewindow"
	// HyprlandEventTypeActivewindowv2 is a HyprlandEventType of type activewindowv2.
	HyprlandEventTypeActivewindowv2 HyprlandEventType = "activewindowv2"
	// HyprlandEventTypeActivelayout is a HyprlandEventType of type activelayout.
	HyprlandEventTypeActivelayout HyprlandEventType = "activelayout"
	// HyprlandEventTypeWorkspace is a HyprlandEventType of type workspace.
	HyprlandEventTypeWorkspace HyprlandEventType = "workspace"
	// HyprlandEventTypeMoveworkspace is a HyprlandEventType of type moveworkspace.
	HyprlandEventTypeMoveworkspace HyprlandEventType = "moveworkspace"
	// HyprlandEventTypeMoveworkspacev2 is a HyprlandEventType of type moveworkspacev2.
	HyprlandEventTypeMoveworkspacev2 HyprlandEventType = "moveworkspacev2"
	// HyprlandEventTypeMonitoradded is a HyprlandEventType of type monitoradded.
	HyprlandEventTypeMonitoradded HyprlandEventType = "monitoradded"
	// HyprlandEventTypeMonitoraddedv2 is a HyprlandEventType of type monitoraddedv2.
	HyprlandEventTypeMonitoraddedv2 HyprlandEventType = "monitoraddedv2"
	// HyprlandEventTypeMonitorremoved is a HyprlandEventType of type monitorremoved.
	HyprlandEventTypeMonitorremoved HyprlandEventType = "monitorremoved"
	// HyprlandEventTypeMonitorremovedv2 is a HyprlandEventType of type monitorremovedv2.
	HyprlandEventTypeMonitorremovedv2 HyprlandEventType = "monitorremovedv2"
	// HyprlandEventTypeFocusedmon is a HyprlandEventType of type focusedmon.
	HyprlandEventTypeFocusedmon HyprlandEventType = "focusedmon"
	// HyprlandEventTypeFocusedmonv2 is a HyprlandEventType of type focusedmonv2.
	HyprlandEventTypeFocusedmonv2 HyprlandEventType = "focusedmonv2"
	// HyprlandEventTypeOpenlayer is a HyprlandEventType of type openlayer.
	HyprlandEventTypeOpenlayer HyprlandEventType = "openlayer"
	// HyprlandEventTypeDestroyworkspace is a HyprlandEventType of type destroyworkspace.
	HyprlandEventTypeDestroyworkspace HyprlandEventType = "destroyworkspace"
	// HyprlandEventTypeDestroyworkspacev2 is a HyprlandEventType of type destroyworkspacev2.
	HyprlandEventTypeDestroyworkspacev2 HyprlandEventType = "destroyworkspacev2"
	// HyprlandEventTypeConfigreloaded is a HyprlandEventType of type configreloaded.
	HyprlandEventTypeConfigreloaded HyprlandEventType = "configreloaded"
	// HyprlandEventTypeUnknown is a HyprlandEventType of type unknown.
	HyprlandEventTypeUnknown HyprlandEventType = "unknown"
)

var ErrInvalidHyprlandEventType = errors.New("not a valid HyprlandEventType")

// String implements the Stringer interface.
func (x HyprlandEventType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x HyprlandEventType) IsValid() bool {
	_, err := ParseHyprlandEventType(string(x))
	return err == nil
}

var _HyprlandEventTypeValue = map[string]HyprlandEventType{
	"activewindow":       HyprlandEventTypeActivewindow,
	"activewindowv2":     HyprlandEventTypeActivewindowv2,
	"activelayout":       HyprlandEventTypeActivelayout,
	"workspace":          HyprlandEventTypeWorkspace,
	"moveworkspace":      HyprlandEventTypeMoveworkspace,
	"moveworkspacev2":    HyprlandEventTypeMoveworkspacev2,
	"monitoradded":       HyprlandEventTypeMonitoradded,
	"monitoraddedv2":     HyprlandEventTypeMonitoraddedv2,
	"monitorremoved":     HyprlandEventTypeMonitorremoved,
	"monitorremovedv2":   HyprlandEventTypeMonitorremovedv2,
	"focusedmon":         HyprlandEventTypeFocusedmon,
	"focusedmonv2":       HyprlandEventTypeFocusedmonv2,
	"openlayer":          HyprlandEventTypeOpenlayer,
	"destroyworkspace":   HyprlandEventTypeDestroyworkspace,
	"destroyworkspacev2": HyprlandEventTypeDestroyworkspacev2,
	"configreloaded":     HyprlandEventTypeConfigreloaded,
	"unknown":            HyprlandEventTypeUnknown,
}

// ParseHyprlandEventType attempts to convert a string to a HyprlandEventType.
func ParseHyprlandEventType(name string) (HyprlandEventType, error) {
	if x, ok := _HyprlandEventTypeValue[name]; ok {
		return x, nil
	}
	return HyprlandEventType(""), fmt.Errorf("%s is %w", name, ErrInvalidHyprlandEventType)
}
